-- ZQM Suite: New Tables Migration
-- Non-Conformances, CAPAs, Handling Units, Lab Analyses, CoA Logs

CREATE TABLE IF NOT EXISTS yuktira_qm.non_conformances (
    "Id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "TenantId" uuid NOT NULL,
    "NCNumber" text NOT NULL DEFAULT '',
    "NCType" text NOT NULL DEFAULT 'Defect',
    "Severity" text NOT NULL DEFAULT 'Minor',
    "Status" text NOT NULL DEFAULT 'Open',
    "MaterialCode" text NOT NULL DEFAULT '',
    "MaterialName" text NOT NULL DEFAULT '',
    "BatchNumber" text NOT NULL DEFAULT '',
    "Plant" text NOT NULL DEFAULT '',
    "InspectionLotNumber" text NOT NULL DEFAULT '',
    "DefectCodeGroup" text NOT NULL DEFAULT '',
    "DefectCode" text NOT NULL DEFAULT '',
    "DefectDescription" text NOT NULL DEFAULT '',
    "RootCauseCategory" text NOT NULL DEFAULT '',
    "RootCauseDescription" text NOT NULL DEFAULT '',
    "DetectedBy" text NOT NULL DEFAULT '',
    "DetectedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "VendorCode" text NOT NULL DEFAULT '',
    "AffectedQuantity" decimal(18,4) NOT NULL DEFAULT 0,
    "EstimatedCost" decimal(18,2) NOT NULL DEFAULT 0,
    "ContainmentAction" text NOT NULL DEFAULT '',
    "IsContainmentActive" boolean NOT NULL DEFAULT FALSE,
    "ContainmentExpiry" timestamp with time zone,
    "Priority" text NOT NULL DEFAULT 'Medium',
    "AssignedTo" text NOT NULL DEFAULT '',
    "DueDate" timestamp with time zone,
    "ClosedAt" timestamp with time zone,
    "ClosedBy" text NOT NULL DEFAULT '',
    "ClosureNotes" text NOT NULL DEFAULT '',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_nc_number ON yuktira_qm.non_conformances ("NCNumber");

CREATE TABLE IF NOT EXISTS yuktira_qm.capas (
    "Id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "TenantId" uuid NOT NULL,
    "CPNumber" text NOT NULL DEFAULT '',
    "CPType" text NOT NULL DEFAULT 'Corrective',
    "Status" text NOT NULL DEFAULT 'Draft',
    "NonConformanceId" text NOT NULL DEFAULT '',
    "NCNumber" text NOT NULL DEFAULT '',
    "Title" text NOT NULL DEFAULT '',
    "Description" text NOT NULL DEFAULT '',
    "RootCauseCategory" text NOT NULL DEFAULT '',
    "RootCauseAnalysis" text NOT NULL DEFAULT '',
    "CorrectiveAction" text NOT NULL DEFAULT '',
    "PreventiveAction" text NOT NULL DEFAULT '',
    "ResponsiblePerson" text NOT NULL DEFAULT '',
    "PlannedCompletionDate" timestamp with time zone,
    "ActualCompletionDate" timestamp with time zone,
    "VerificationMethod" text NOT NULL DEFAULT '',
    "VerifiedBy" text NOT NULL DEFAULT '',
    "VerifiedAt" timestamp with time zone,
    "EffectivenessConfirmed" boolean NOT NULL DEFAULT FALSE,
    "EffectivenessNotes" text NOT NULL DEFAULT '',
    "VendorPenaltyAmount" text NOT NULL DEFAULT '',
    "VendorPenaltyType" text NOT NULL DEFAULT '',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_cp_number ON yuktira_qm.capas ("CPNumber");

CREATE TABLE IF NOT EXISTS yuktira_qm.handling_units (
    "Id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "TenantId" uuid NOT NULL,
    "HUNumber" text NOT NULL DEFAULT '',
    "MaterialCode" text NOT NULL DEFAULT '',
    "MaterialName" text NOT NULL DEFAULT '',
    "BatchNumber" text NOT NULL DEFAULT '',
    "Plant" text NOT NULL DEFAULT '',
    "StorageLocation" text NOT NULL DEFAULT '',
    "WarehouseNumber" text NOT NULL DEFAULT '',
    "PackagingMaterial" text NOT NULL DEFAULT '',
    "Quantity" decimal(18,4) NOT NULL DEFAULT 0,
    "BaseUOM" text NOT NULL DEFAULT 'EA',
    "GrossWeight" decimal(18,4) NOT NULL DEFAULT 0,
    "NetWeight" decimal(18,4) NOT NULL DEFAULT 0,
    "WeightUOM" text NOT NULL DEFAULT 'KG',
    "Volume" decimal(18,4) NOT NULL DEFAULT 0,
    "VolumeUOM" text NOT NULL DEFAULT 'L',
    "PackageType" text NOT NULL DEFAULT 'Standard',
    "Status" text NOT NULL DEFAULT 'Created',
    "InspectionLotNumber" text NOT NULL DEFAULT '',
    "QualityStatus" text NOT NULL DEFAULT '',
    "PackedAt" timestamp with time zone,
    "PackedBy" text NOT NULL DEFAULT '',
    "ReleasedAt" timestamp with time zone,
    "ReleasedBy" text NOT NULL DEFAULT '',
    "DeliveryNoteNumber" text NOT NULL DEFAULT '',
    "ShipmentNumber" text NOT NULL DEFAULT '',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_hu_number ON yuktira_qm.handling_units ("HUNumber");

CREATE TABLE IF NOT EXISTS yuktira_qm.lab_analyses (
    "Id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "TenantId" uuid NOT NULL,
    "AnalysisNumber" text NOT NULL DEFAULT '',
    "MaterialCode" text NOT NULL DEFAULT '',
    "MaterialName" text NOT NULL DEFAULT '',
    "BatchNumber" text NOT NULL DEFAULT '',
    "Plant" text NOT NULL DEFAULT '',
    "InspectionLotNumber" text NOT NULL DEFAULT '',
    "CalculationType" text NOT NULL DEFAULT '',
    "RawValue" decimal(18,6) NOT NULL DEFAULT 0,
    "InputUnit" text NOT NULL DEFAULT '',
    "ConvertedValue" decimal(18,6) NOT NULL DEFAULT 0,
    "OutputUnit" text NOT NULL DEFAULT '',
    "LSL" decimal(18,6) NOT NULL DEFAULT 0,
    "USL" decimal(18,6) NOT NULL DEFAULT 0,
    "IsWithinSpec" boolean NOT NULL DEFAULT TRUE,
    "Evaluation" text NOT NULL DEFAULT '',
    "Formula" text NOT NULL DEFAULT '',
    "AnalyzedBy" text NOT NULL DEFAULT '',
    "AnalyzedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "Method" text NOT NULL DEFAULT '',
    "InstrumentId" text NOT NULL DEFAULT '',
    "Notes" text NOT NULL DEFAULT '',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_lab_analysis_number ON yuktira_qm.lab_analyses ("AnalysisNumber");

CREATE TABLE IF NOT EXISTS yuktira_qm.coa_generation_logs (
    "Id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "TenantId" uuid NOT NULL,
    "CertificateNumber" text NOT NULL DEFAULT '',
    "InspectionLotNumber" text NOT NULL DEFAULT '',
    "MaterialCode" text NOT NULL DEFAULT '',
    "BatchNumber" text NOT NULL DEFAULT '',
    "CustomerCode" text NOT NULL DEFAULT '',
    "CustomerName" text NOT NULL DEFAULT '',
    "TotalCharacteristics" integer NOT NULL DEFAULT 0,
    "PassedCharacteristics" integer NOT NULL DEFAULT 0,
    "FailedCharacteristics" integer NOT NULL DEFAULT 0,
    "OverallResult" text NOT NULL DEFAULT '',
    "GeneratedBy" text NOT NULL DEFAULT '',
    "GeneratedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "Status" text NOT NULL DEFAULT 'Issued',
    "DeliveryNoteNumber" text NOT NULL DEFAULT '',
    "MovementDocumentNumber" text NOT NULL DEFAULT '',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_coa_log_number ON yuktira_qm.coa_generation_logs ("CertificateNumber");
