using Microsoft.EntityFrameworkCore;
using YuktiraERP.Core.Dtos;
using YuktiraERP.Core.Interfaces;
using YuktiraERP.Infrastructure.Data;
using YuktiraERP.Infrastructure.Data.Entities;

namespace YuktiraERP.Infrastructure.Services;

public class AutoInspectionPlanGenerator : IAutoInspectionPlanGenerator
{
    private readonly YuktiraDbContext _db;
    private readonly ITenantContext _tenant;
    private readonly IAuditService _audit;
    private readonly IInspectionPlanService _planService;

    public AutoInspectionPlanGenerator(
        YuktiraDbContext db,
        ITenantContext tenant,
        IAuditService audit,
        IInspectionPlanService planService)
    {
        _db = db;
        _tenant = tenant;
        _audit = audit;
        _planService = planService;
    }

    public async Task<InspectionPlanDto> GeneratePlanAsync(AutoGenerationRequest request, Guid tenantId)
    {
        var createRequest = new InspectionPlanCreateRequest
        {
            PlantId = request.PlantId,
            MaterialId = request.MaterialId,
            Usage = "5",
            Description = $"Auto-generated inspection plan for {request.MaterialId}",
            LotSizeFrom = 1,
            LotSizeTo = 999999
        };

        var plan = await _planService.CreateGenericPlanAsync(createRequest, tenantId);

        var header = await _db.QmInspectionPlanHeaders.FirstAsync(h => h.Id == plan.Id);
        header.OverallStatus = "4";
        header.Usage = "5";
        header.LotSizeFrom = 1;
        header.LotSizeTo = 999999;

        var defaultOperation = await _db.QmInspectionPlanOperations
            .FirstAsync(o => o.PlanHeaderId == plan.Id);
        defaultOperation.OperationDescription = "Standard Quality Inspection";
        await _db.SaveChangesAsync();

        var releasedMics = await _db.Set<MicMasterEntity>()
            .Where(m => m.TenantId == tenantId
                && m.PlantId == request.PlantId
                && m.Status == "Released")
            .ToListAsync();

        if (!string.IsNullOrEmpty(request.ProductCategory))
        {
            var categoryMics = releasedMics
                .Where(m => m.ShortText.Contains(request.ProductCategory, StringComparison.OrdinalIgnoreCase))
                .ToList();
            if (categoryMics.Any())
                releasedMics = categoryMics;
        }

        int charNo = 1;
        foreach (var mic in releasedMics)
        {
            var micAssign = new InspectionPlanMicAssignRequest
            {
                OperationId = defaultOperation.Id,
                CharacteristicNo = charNo++,
                MicCode = mic.CharacteristicCode,
                MicPlantId = mic.PlantId,
                IsQuantitative = mic.IsQuantitative,
                ShortText = mic.ShortText,
                InspectionMethodCode = mic.InspectionMethodCode,
                SamplingProcedureCode = "SP-001"
            };

            var micEntity = new QmInspectionPlanMicEntity
            {
                TenantId = tenantId,
                PlanHeaderId = plan.Id,
                OperationId = defaultOperation.Id,
                CharacteristicNo = micAssign.CharacteristicNo,
                MicCode = micAssign.MicCode,
                MicPlantId = micAssign.MicPlantId,
                MicVersion = mic.Version,
                IsQuantitative = micAssign.IsQuantitative,
                ShortText = micAssign.ShortText,
                InspectionMethodCode = micAssign.InspectionMethodCode,
                InspectionMethodVersion = mic.InspectionMethodVersion,
                SamplingProcedureCode = micAssign.SamplingProcedureCode
            };

            _db.QmInspectionPlanMics.Add(micEntity);
        }

        await _db.SaveChangesAsync();

        await _audit.LogAsync(new AuditEntryDto
        {
            TenantId = tenantId,
            ModuleName = "QM",
            ActionType = YuktiraERP.Core.Domain.Common.ActionType.Create,
            EntityName = "QmInspectionPlanHeader",
            EntityId = plan.Id.ToString(),
            NewValue = System.Text.Json.JsonSerializer.Serialize(new
            {
                plan.GroupKey,
                request.PlantId,
                request.MaterialId,
                MicCount = releasedMics.Count,
                AutoGenerated = true
            })
        });

        return await _planService.GetPlanAsync(plan.Id, tenantId)
            ?? throw new InvalidOperationException("Failed to retrieve auto-generated plan.");
    }
}
